name: 定时部署

on:
  schedule:
    # 每5小时执行一次
    # GitHub Actions 每5小时自动触发一次部署
    - cron: "0 */5 * * *"
  workflow_dispatch:       # 也支持手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 触发 EdgeOne 部署钩子
        run: |
          curl -fsS -X POST "https://pages-api.cloud.tencent.com/v1/webhook/07f6dbd000a5f0a65b433994a151551022b39f1dcb8fcb0080c42979c74fc103"